### ISSUE TITLE
openSUSE: Switch to Leap, use patterns

### ISSUE THREAD

**Issue by lbeltrame** [Wenzel/docker-kdesrc-build#13]
The recent openSUSE Leap 42.1 release is more suited to build KDE software as it has lots of new libraries. Furthermore, some development packages could be installed via patterns, to reduce the number items listed.

NOTE: I'm hoping to do this work myself, but I'm not sure how to test it once done. Any pointers?

**Comment by Wenzel** [comment]
Hi _lbeltrame_,

yes, Opensuse could be a better choice to build KDE since it is very well integrated.

I choose Archlinux as the default distribution because I had some issues with some KDE repositories which had some dependencies with build dependencies not yet available in Opensuse's repos.

Unfortunately, I don't see this new release in the [docker hub registry](https://hub.docker.com/_/opensuse/), since the latest image is pointing to the tag `13.2`.

However, if you would like to try, you could build your own Opensuse `42.1` docker image locally,
replace `FROM opensuse:13.2` -> `FROM myopensuse`, and run `./run.py -b opensuse` to build the new image
If the everything is OK, then try to build all KDE repositories with `kdesrc-build` tool.
This is already configured in the provided file `kdesrc-buildrc`

```
...
include ./kdesrc-build/kf5-frameworks-build-include
include ./kdesrc-build/kf5-workspace-build-include
include ./kdesrc-build/kf5-applications-build-include
...
```

Thank you for testing !
